### ISSUE TITLE
Firefox CSS Styling Recommendations

### ISSUE THREAD

**Issue by JayXT** [Ajatt-Tools/rikaitan#119]
Hello,

Is there a similar guide for CSS styling, but targeting Firefox?
https://tatsumoto.neocities.org/blog/setting-up-yomichan#styling

It seems like Firefox doesn't correctly respond to tag/tag font size changes. For example, on the following screenshot Brave with Yomichan is on the left and Firefox with Rikaitan is on the right:

![image](https://github.com/Ajatt-Tools/rikaitan/assets/8045344/76d099fa-ff2a-4aea-9676-659765338fd3)

A few noticeable things here when it comes to Firefox are: the distance between furigana and kanji is larger, tag sizes are huge.

Do you have any suggestions how this could be improved?

P.S. Profile selector is not visible in Firefox, since I hid it to save space with the following CSS:
`#profile-select { display: none; }`
`#search-option-profile-select { display: none; }`

**Comment by tatsumoto-ren** [comment]
>Is there a similar guide for CSS styling, but targeting Firefox?

On Firefox CSS can be changed the same way. Some things may look slightly different, but I don't think it's a huge problem. 

> It seems like Firefox doesn't correctly respond to tag/tag font size changes.

If you use relative units, the font size will depend on a lot of things, including the font size of the parent elements.

I personally use the following settings

```css

[data-page-type="popup"] .gloss-content  {
    font-size: clamp(1rem, 6.5vw, 4rem);
    font-weight: 300;
}
[data-page-type="popup"] .tag-label-content {
    font-size: 3vw;
    font-weight: 300;
}

[data-page-type="search"] .gloss-content {
    font-size: 2rem;
}
```
I find that the vw unit works better when reading while zoomed in.
